[package]
name = "upaint"
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = { version = "0.23.0", features = ["all-widgets"] }
anyhow = "1.0.75"
crossterm = { version = "0.27.0", features = ["serde"] }
clap = { version= "4.4.2", features = ["derive"] }
config = "0.13.3"
serde = { version = "1.0.188", features = ["derive"] }
toml = "0.8.0"
ratatui-textarea = "0.3.2"
hsv = "0.1.1"


[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "test_export"
path = "src/test_export.rs"

[[bin]]
name = "test_import"
path = "src/test_import.rs"

[[bin]]
name = "test_config"
path = "src/test_config.rs"
