[package]
name = "keystrokes_parsing"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
crossterm = { version = "0.28.1", features = ["serde"] }
derive_more = "0.99.18"
keystrokes_parsing_derive = { path = "keystrokes_parsing_derive" }
