# All alternatives are listed in `color_theme_presets!(...)` in `src/config/color_theme.rs`
color_theme_preset = "Basic"

# Row numbers
[numbers.row]
enable = true
relative = false

# Column numbers
[numbers.column]
enable = true
relative = false

[keymaps.actions]
"u" = { "Undo" = {} }
"<C-r>" = { "Redo" = {} }
":" = { "ModeCommand" = {} }
"i" = { "ModeInsert" = { jump = "Diagonals" } }
"gc" = { "ModeColorPicker" = { slot = "Active" } }
"gp" = { "Pipette" = { slot = "Active" }}
"v" = { ModeVisualRect = {} }
"o" = { SetSelectionActive = { highlight = true } }
'"' = { SetYankActive = {} }
"O" = { HighlightSelectionClear = {} }
"P" = { Paste = {} }
"p" = { Paste = { slot = "Active" } }
"r" = { Operation = { motion = { Stay = {}}, operator = { Replace = {}}}}
"R" = { Operation = { operator = { Replace = {}}}}
"m" = { MarkSet = {}}
"#" = { SetColorOrSlotActive = {} }
"Kr" = { Operation = { motion = { Stay = {}}, operator = { Replace = { ch = "h"}}}}
# "" = { Operation = { operator = { Replace = { ch = "h"}}}}
# "" = { MoveCursor = { motion = { FixedNumberOfCells = {  }
"" = { MoveCursor = {}}

[keymaps.operators]
"c" = { "Colorize" = { ground = "Foreground", color = "Active" } }
"C" = { "Colorize" = { ground = "Foreground" } }
"b" = { "Colorize" = { ground = "Background", color = "Active" } }
"B" = { "Colorize" = { ground = "Background" } }
"r" = { Replace = {} }
"S" = { UpdateSelection = { highlight = true } }
"a" = { UpdateSelection = { operator = "Add", slot = "Active", highlight = true } }
"z" = { UpdateSelection = { operator = "Subtract", slot = "Active", highlight = true } }
"s" = { UpdateSelection = { operator = "Overwrite", slot = "Active", highlight = true } }
"y" = { Yank = { content_type = "ALL", slot = "Active" } }
"D" = { Cut = { content_type = "ALL" } }
"d" = { Cut = { content_type = "ALL", slot = "Active" } }

[keymaps.motions]
" " = { Stay = {} }
"n" = { FixedNumberOfCells = { jump = "Diagonals" } }
"w" = { WordBoundary = { boundary_type = "START" } }
"e" = { WordBoundary = { boundary_type = "END" } }
"f" = { FindChar = {} }
"," = { FindCharRepeat = { direction_reversed = false } }
";" = { FindCharRepeat = { direction_reversed = true } }
"S" = { SelectionMotion = {} }
"s" = { SelectionMotion = { slot = "Active" } }
"J" = { GoToMark = { jump = "Diagonals" } }
"L" = { GoToMark = { jump = "Diagonals", slot = "l" } }
"A" = { MatchingCells = {} }
"i" = { ContinuousRegion = { diagonals_allowed = false } }
"a" = { ContinuousRegion = { diagonals_allowed = true } }
"" = { FixedNumberOfCells = { number_of_cells = 1, jump = "DirectionAsStride" }}

[keymaps.directions]
"h" = [0, -1]
"j" = [1, 0]
"k" = [-1, 0]
"l" = [0, 1]
"y" = [-1, -2]
"u" = [-1, -1]
"i" = [-1, 1]
"o" = [-1, 2]
"n" = [1, -2]
"m" = [1, -1]
"," = [1, 1]
"." = [1, 2]

[keymaps.grounds]
"f" = "Foreground"
"b" = "Background"

[keymaps.characters]
"<C-u>-" = "—"

[keymaps.bools]
"f" = false
"t" = true
"n" = false
" " = true

[keymaps.word_boundary_types]
"a" = "ANY"
"s" = "START"
"e" = "END"

[keymaps.colors]
" " = "Reset"
"b" = "Black"
"r" = "Red"
"g" = "Green"
"y" = "Yellow"
"l" = "Blue"
"m" = "Magenta"
"c" = "Cyan"
"w" = "Gray" # Non-bright white
"B" = "DarkGray" # Bright black
"R" = "LightRed"
"G" = "LightGreen"
"Y" = "LightYellow"
"L" = "LightBlue"
"M" = "LightMagenta"
"C" = "LightCyan"
"W" = "White"
# "s" = { Slot = "s" }

[keymaps.color_or_slots]
# "s" = { Slot = "FromKeystrokes" }
# "" = { Color = "FromKeystrokes" }

[keymaps.test]
"h" = { a = "FromKeystrokes" }

[keymaps.color_or_slot_specifications]

[keymaps.canvas_iteration_jumps]
# "d" = "Diagonals"
"s" = "DirectionAsStride"

[keymaps.update_selection_operators]
"a" = "Add"
"s" = "Overwrite"
"z" = "Subtract"

[keymaps.cell_content_types]
"n" = "NONE"
"a" = "ALL"
"t" = "TEXT"
"f" = "FG"
"b" = "BG"
"c" = "COLOR"
"F" = "FG | TEXT"
"B" = "BG | TEXT"
"C" = "COLOR | TEXT"
"m" = "MODIFIERS"

[keymaps.continuous_region_relative_types]
"w" = { NonBlank = "TEXT" }
# "W" = { NonBlank = {} }

[keymaps.keymap_u32]
[keymaps.selection_slot_specifications]
[keymaps.yank_slot_specifications]
