[canvas.default_style]
fg = "Reset"
bg = "Reset"
modifiers = ""

[canvas.standard_colors]
black = "Black"
red = "Red"
green = "Green"
yellow = "Yellow"
blue = "Blue"
magenta = "Magenta"
cyan = "Cyan"
white = "Gray"
bright_black = "DarkGray"
bright_red = "LightRed"
bright_green = "LightGreen"
bright_yellow = "LightYellow"
bright_blue = "LightBlue"
bright_magenta = "LightMagenta"
bright_cyan = "LightCyan"
bright_white = "White"

[status_bar]
fg = "White"
bg = "DarkGray"
modifiers = ""

[command_line]
fg = "Reset"
bg = "Reset"
modifiers = ""

[input_mode]
fg = "Reset"
bg = "Reset"
modifiers = "BOLD"

[user_feedback]
fg = "Reset"
bg = "Reset"
modifiers = ""
