[color_theme.status_bar]
fg = "Black"
bg = "Gray"

[color_theme.command_line]
fg = "Black"
bg = "White"

[color_theme.input_mode]
fg = "Black"
bg = "White"

[color_theme.user_feedback]
fg = "Black"
bg = "White"

[color_theme.canvas.default_style]
fg = "Black"
bg = "White"
